name: CLI Verify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cli-verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate themes
        run: npm run generate

      - name: Run installer
        run: |
          export HOME=$(mktemp -d)
          ./cli/install.sh

      - name: Run verifier
        run: |
          export HOME=$(mktemp -d)
          ./cli/install.sh
          ENGINE=docker ./verify/verify.sh
